joint_names: [base_left_omniwheel_joint, base_right_omniwheel_joint, base_back_omniwheel_joint]

joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

## velocity controller
joint_group_velocity_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
     - base_left_omniwheel_joint
     - base_right_omniwheel_joint
     - base_back__omniwheel_joint
  required_drive_mode: 3

base_left_omniwheel_joint_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: base_left_omniwheel_joint
  required_drive_mode: 3

base_right_omniwheel_joint_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: base_right_omniwheel_joint
  required_drive_mode: 3

base_back_omniwheel_joint_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: base_back_omniwheel_joint
  required_drive_mode: 3
