#
# File description of the mobile base geometry, assuming a 3 wheels holonomic robot.
#

holonomic_base: 
  wheel_radius: 0.04
  base_radius: 0.2
  maximum_velocity_rpm: 50
  gearbox_ratio_num: 128
  gearbox_ratio_den: 1
