#
# Open Source Android - configuration file
#
# Parameters:
#
# type:
#    TENDON
#    CLASSICAL
#    SEA
#    WHEEL
#
# controller:
#    NOT_USED
#    EPOS2
#    EPOS4
#
# motor:
#    NONE
#    DCX10
#    DCX14
#    DCX16
#    DCX22
#    DCX32
#    RE13
#    RE30
#    ECI40
#    ECI52
#    EC32F_12
#    EC32F_24
#    EC90
#
# inverted:
#    false
#    true
#
# mode: mode of operation selected during initialization: 
#    INTERPOLATED_POSITION_MODE
#    PROFILE_VELOCITY_MODE
#    PROFILE_POSITION_MODE
#    POSITION_MODE
#    VELOCITY_MODE
#    CURRENT_MODE
#    CYCLIC_SYNCHRONOUS_TORQUE_MODE
#
# value: default value that will be sent after EPOS board initialization, according to the selected mode of operation
# 

robot:
  name: 'airp1_foldy_base'
  dof: 3  # Number of Degrees Of Freedom.
  can_device: 'can0'
  heartbeat: 50

# Base
dof1: {name: 'wheel/left', type: 'WHEEL', node_id: 1, controller: 'EPOS4', motor: 'ECI40', inverted: false, mode: 'PROFILE_VELOCITY_MODE', value: 0}
dof2: {name: 'wheel/right', type: 'WHEEL', node_id: 2, controller: 'EPOS4', motor: 'ECI40', inverted: false, mode: 'PROFILE_VELOCITY_MODE', value: 0}
dof3: {name: 'wheel/back', type: 'WHEEL', node_id: 3, controller: 'EPOS4', motor: 'ECI40', inverted: false, mode: 'PROFILE_VELOCITY_MODE', value: 0}

